name  = "SpriteLayer"
url   = "http://www.spritelayerradio.com:8010/all"
blurb = "US -- video game soundtracks"
tags  = ["games"]
logo  = "http://www.spritelayerradio.com/static/icons/production/180.png"
